# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
      
    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: dotnet new globaljson --roll-forward feature
    
    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: (Get-ItemPropertyValue -LiteralPath 'HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full' -Name Release) -ge 378389
      
    - name: pwd
      run: ls

    - name: pwd
      run: pwd
      
    - name: Move Folder
      run: cd D:\a\DOTNET\DOTNET\DotNet4.5-ApiGateway\
      
    - name: pwd
      run: ls
    
    - name: path
      run: pwd
    
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-build --verbosity normal
